// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfakcygiooabsikksets.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmYWtjeWdpb29hYnNpa2tzZXRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNDE1MzksImV4cCI6MjA2OTcxNzUzOX0.aDcfFXqqKjPHwUWKuiu-Vmau12kS7xNonKXzHBHpi3E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});